// Code generated by go generate; DO NOT EDIT.
// 2018-05-21 18:57:34.912062282 +0300 MSK m=+0.006342684

package template

var templateNewsViewsMap = map[string]string{
	"news_home": `{{ define "title"}}{{ t "Home" }}{{ end }}

{{ define "content"}}
<section class="page-header">
    <h1>{{ t "Home" }}</h1>
    <ul>
        <li>
            <a href="{{ route "settings" }}">{{ t "Settings" }}</a>
        </li>
        <li>
            <a href="{{ route "integrations" }}">{{ t "Integrations" }}</a>
        </li>
    </ul>
</section>

<div class="panel">
    <h3>{{ t "Authors" }}</h3>
    <ul>
        <li><strong>{{ t "Author:" }}</strong> Frédéric Guillot</li>
        <li><strong>{{ t "License:" }}</strong> Apache 2.0</li>
    </ul>
</div>

{{ end }}`,
}

var templateNewsViewsMapChecksums = map[string]string{
	"home": "0c4cf565826eb87bc6e2f82c2e57a5c553fa0b88db016e85668276acc2283030",
}
