// Code generated by go generate; DO NOT EDIT.
// 2018-06-24 18:19:32.873083524 +0300 MSK m=+0.006672557

package static

var NewsBinaries = map[string]string{}

var NewsBinariesChecksums = map[string]string{}
