// Code generated by go generate; DO NOT EDIT.
// 2018-07-28 13:28:03.460655952 +0300 MSK m=+0.006389835

package static

var NewsBinaries = map[string]string{}

var NewsBinariesChecksums = map[string]string{}
