// Code generated by go generate; DO NOT EDIT.
// 2018-07-08 18:17:24.505106188 +0300 MSK m=+0.006723271

package static

var NewsBinaries = map[string]string{}

var NewsBinariesChecksums = map[string]string{}
