// Code generated by go generate; DO NOT EDIT.
// 2018-05-18 18:53:11.030576519 +0300 MSK m=+0.004555829

package static

var NewsStylesheets = map[string]string{
	"news": `*{margin:0;padding:0;box-sizing:border-box}`,
}

var NewsStylesheetsChecksums = map[string]string{
	"news": "5bf5cc51c008fcabcde7431f6d2d0d158471f99063c27d4c8635cb4368b263cd",
}
