// Code generated by go generate; DO NOT EDIT.
// 2018-05-18 18:53:11.030674386 +0300 MSK m=+0.004653711

package static

var NewsJavascript = map[string]string{
	"app": `(function(){'use strict';});`,
}

var NewsJavascriptChecksums = map[string]string{
	"app": "0470f3bee94c602791256620a52d12e6b76e71bc596eab38dc5e2e78a7e254da",
}
